name: "VSLab Research Manager"

on:
  push:
    branches: [ "main" ]

jobs:
  manage-todo:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Generate Research Issues"
        uses: alstr/todo-to-issue-action@v5
        with:
          IDENTIFIERS: '["TODO", "OPTIMIZE", "EXPERIMENT"]'
          LABELS: '["research", "todo"]'
          INSERT_LABEL: true
